version: "3"

services:
  api:
    environment:
      TZ: "UTC"
      DB_HOST: hello-server-postgres-1
      DB_database: hello
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./src:/app/src

  postgres:
    image: postgres:17.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hello
      TZ: "UTC"
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
